release:
  stage: build
  image: maven:3.6.2-jdk-8
  tags:
    - docker
  script:
    - mvn install:install-file -Dfile=lib/ADEAde.jar -DgroupId=com.adesoft -DartifactId=ade -Dversion=6.8.0 -Dpackaging=jar -DgeneratePom=true
    - mvn install:install-file -Dfile=lib/ADEConfig.jar -DgroupId=com.adesoft -DartifactId=config -Dversion=6.8.0 -Dpackaging=jar -DgeneratePom=true
    - mvn install:install-file -Dfile=lib/ADEJDom.jar -DgroupId=com.adesoft -DartifactId=jdom -Dversion=6.8.0 -Dpackaging=jar -DgeneratePom=true
    - mvn install:install-file -Dfile=lib/ADEMisc.jar -DgroupId=com.adesoft -DartifactId=misc -Dversion=6.8.0 -Dpackaging=jar -DgeneratePom=true
    - mvn package
    - mkdir _public
    - cp target/ade-sync* _public
    - mv _public public
  artifacts:
    paths:
      - public